INSERT INTO departamentos (codigo, descripcion) VALUES 
('001', 'Bogota'),
('002', 'Amazonas'),
('003', 'Antioquia'),
('004', 'Arauca'),
('005', 'Atlantico'),
('006', 'Bolivar'),
('007', 'Boyaca'),
('008', 'Caldas'),
('009', 'Caqueta'),
('010', 'Casanare'),
('011', 'Cauca'),
('012', 'Cesar'),
('013', 'Choco'),
('014', 'Cordoba'),
('015', 'Cundinamarca'),
('016', 'Guainia'),
('017', 'Guaviare'),
('018', 'Huila'),
('019', 'La Guajira'),
('020', 'Magdalena'),
('021', 'Meta'),
('022', 'Nariño'),
('023', 'Norte de Santander'),
('024', 'Putumayo'),
('025', 'Quindio'),
('026', 'Risaralda'),
('027', 'San Andres y Providencia'),
('028', 'Santander'),
('029', 'Sucre'),
('030', 'Tolima'),
('031', 'Valle del Cauca'),
('032', 'Vaupes'),
('033', 'Vichada');

INSERT INTO tipos_documento (codigo, descripcion) VALUES 
('CC', 'Cédula de ciudadanía'),
('CE', 'Cédula de extranjería'),
('PP', 'Pasaporte'),
('TI', 'Tarjeta de Identidad'),
('RC', 'Registro civil de nacimiento'),
('NIT', 'Número de Identificación Tributaria');